Spring:
  jpa:
      generate-ddl: 'true'
      defer-datasource-initialization: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'
      database-platform: org.hibernate.dialect.H2Dailect
      properties:
          hibernate:
             format_sql: 'true'
  h2:
      cosole:
          path: /h2-console
          enable: 'true'
  datasource:
    password: ''
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:marcasus
    server:
      port: ${port:8080}
